services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=netflix_db 
    volumes:
      - "./volume:/var/lib/postgresql/data"
    ports:
      - 5432:5432

  pgadmim:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_PASSWORD=root
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
    ports:
      - 8080:80
